### login
POST localhost:9999/user/login
Content-Type: application/json

{
  "email" : "john",
  "password" : "345"
}

### register
POST localhost:9999/users/register
Content-Type: application/json

{
  "email" : "john",
  "password" : "345",
  "verifiedPassword" : "345"
}

### get by id
GET localhost:9999/users/14
Content-Type: application/json

### edit
PUT localhost:9999/users
Content-Type: application/json

{
  "id" : 1,
  "username" : "john",
  "password" : "345"
}

### delete
DELETE localhost:9999/users/1

### LOGOUT
POST localhost:9999/users