### login
POST localhost:9999/login
Content-Type: application/json

{
  "email": "mysite@ourearth.com",
  "password": "MorskoKonche3!"
}

### register
POST localhost:9999/register
Content-Type: application/json

{
  "email": "na@ourearth.com",
  "password": "MorskoKonche3!",
  "confirmedPassword": "MorskoKonche3!",
  "firstName": "John",
  "lastName": "Ivanov",
  "gender": "m",
  "phoneNumber": "0987589195",
  "isHost": "false"
}

### get by id
GET localhost:9999/1
Content-Type: application/json

### edit
PUT localhost:9999/edit
Content-Type: application/json

{
  "id": 1,
  "username": "john",
  "password": "345"
}

### delete
DELETE localhost:9999/1
{
  "id": 1
}

### LOGOUT
POST localhost:9999/logout