### addProperty
POST localhost:9999/add
Content-Type: application/json

{
  "propertyType": "vila",
  "bedrooms" : 2,
  "bathrooms" : 3,
  "guests" : 2,
  "pricePerNight": 120,
  "description": "cozy",
  "country": "Poland",
  "city": "Krakow",
  "street": "Svoboda",
  "zipCode": "2345",
  "apartmentNumber": 4
}

### getPropertyById
GET localhost:9999/properties/14
Content-Type: application/json

### deletePropertyById
DELETE localhost:9999/delete/15