### addProperty
POST localhost:9999/add
Content-Type: application/json

{
  "propertyType": "guesthouse",
  "bedrooms": 2,
  "bathrooms": 3,
  "guests": 2,
  "pricePerNight": 120,
  "description": "cozy",
  "country": "Bulgaria",
  "city": "Sofia",
  "street": "Svoboda",
  "zipCode": "1212",
  "hasWifi": 1,
  "hasTv": 1,
  "hasAirConditioner": 0,
  "hasFridge": 0,
  "hasKitchenFacilities": 1,
  "hasBreakfast": 1,
  "hasParkingSpot": 1,
  "hasFitness": 0,
  "hasWashingMachine": 1,
  "typeOfBed": "doubleBed"
}

### getPropertyById
GET localhost:9999/properties/5
Content-Type: application/json

### deletePropertyById
DELETE localhost:9999/delete/5
Content-Type: application/json

###editAddress
PUT localhost:9999/edit/address/1
Content-Type: application/json

{
"country": "Bulgaria",
"city": "Sofia",
"street": "Lipa",
"zipCode": "1616",
"apartmentNumber": 2
}

###editCharacteristics
PUT localhost:9999/edit/characteristic/1
Content-Type: application/json

{
  "hasWifi": 0,
  "hasTv": 0,
  "hasAirConditioner": 0,
  "hasFridge": 0,
  "hasKitchenFacilities": 1,
  "hasBreakfast": 1,
  "hasParkingSpot": 1,
  "hasFitness": 0,
  "hasWashingMachine": 1,
  "typeOfBed": "singleBed"
}

###filterPropertyByCharacteristics
GET localhost:9999/filter/by/characteristics
Content-Type: application/json

{
  "country": "Bulgaria",
  "city": "Sofia",
  "bedrooms": 2,
  "bathrooms": 3,
  "guests": 2,
  "hasWifi": 1,
  "hasTv": 1,
  "hasAirConditioner": 0,
  "hasFridge": 0,
  "hasKitchenFacilities": 1,
  "hasBreakfast": 1,
  "hasParkingSpot": 1,
  "hasFitness": 0,
  "hasWashingMachine": 0
}

###filterPropertyByPrice
GET localhost:9999/filter/by/price
Content-Type: application/json

{
  "lowerLimitPrice": 90.0,
  "upperLimitPrice": 140.99
}